# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.synced_folder "../", "/workspace"
  cnfig.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     apt-get install -y python2.7 python-pip python-dev build-essential 
   SHELL
end
